name: charts_common
version: 0.8.0
description: A common library for charting packages.
author: Charts Team <charts_flutter@google.com>
homepage: https://github.com/google/charts

environment:
  sdk: '>=2.1.0 <4.0.0'

dependencies:
  collection: any
  intl: any
  logging: any
  meta: any
  vector_math: any

dev_dependencies:
  mockito: ^4.0.0
  test: ^1.5.3
